{"uuid":"ac58ec4b-4c14-4806-8dbc-416907287ec2","historyId":"d8a97c55520f9524b1d6d61f8ee6e827","fullName":"U546.getTVSMLatestDeviceData.validateFields","labels":[{"name":"package","value":"U546.getTVSMLatestDeviceData"},{"name":"testClass","value":"U546.getTVSMLatestDeviceData"},{"name":"testMethod","value":"validateFields"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"p360_b2c_automation_testing"},{"name":"subSuite","value":"U546.getTVSMLatestDeviceData"},{"name":"host","value":"meghana-Latitude-7490"},{"name":"thread","value":"50981@meghana-Latitude-7490.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"validateFields","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The following asserts failed:\n\todometer value is not matching expected [5665] but found [1280],\n\tlongitude is not matching expected [2] but found [77.55105]","trace":"java.lang.AssertionError: The following asserts failed:\n\todometer value is not matching expected [5665] but found [1280],\n\tlongitude is not matching expected [2] but found [77.55105]\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)\n\tat U546.getTVSMLatestDeviceData.validateFields(getTVSMLatestDeviceData.java:100)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:829)\n\tat org.testng.TestRunner.run(TestRunner.java:602)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\n\tat org.testng.TestNG.run(TestNG.java:1067)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1741353048999,"stop":1741353051951}